package Aplicacion;

import Estructura.ABB;
import Estructura.Producto;
import javax.swing.JOptionPane;

public class Interfaz extends javax.swing.JFrame {

    int a = 0;
    int i = 0;
    int b = 0;
    int c = 0;
    int d = 0;
    int x = 0;
    ABB y = new ABB();

    /** Creates new form Interfz */
    public Interfaz() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtMostrar = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        txtMostrar1 = new javax.swing.JTextField();
        btnMostrar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dibujando Arboles Binarios");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 51)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        btnIngresar.setBackground(new java.awt.Color(204, 204, 204));
        btnIngresar.setFont(new java.awt.Font("BankGothic Lt BT", 1, 14));
        btnIngresar.setText("ingresar");
        btnIngresar.setEnabled(false);
        btnIngresar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnIngresar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1.setText("INTEGRANTES:");

        btnSalir.setBackground(new java.awt.Color(204, 204, 204));
        btnSalir.setFont(new java.awt.Font("BankGothic Lt BT", 1, 14));
        btnSalir.setText("Salir");
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel9.setText("Dibujando Arboles Binarios De Busqueda ABB");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("UNIVERSIDAD TÉCNICA DEL NORTE");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Estructura de datos II");

        jLabel3.setFont(new java.awt.Font("BankGothic Lt BT", 1, 14));
        jLabel3.setText("Nombre");

        txtNombre.setFont(new java.awt.Font("BankGothic Lt BT", 1, 14));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel10.setText("Almacen EAEAE");

        jLabel6.setFont(new java.awt.Font("Italic", 1, 12));
        jLabel6.setText("Edy Maldonado");

        jLabel11.setFont(new java.awt.Font("Italic", 1, 12));
        jLabel11.setText("Angela Perez");

        jLabel12.setFont(new java.awt.Font("Italic", 1, 12));
        jLabel12.setText("Alvaro Arias");

        jLabel13.setFont(new java.awt.Font("Italic", 1, 12));
        jLabel13.setText("Erika Varela");

        jLabel14.setFont(new java.awt.Font("Italic", 1, 12));
        jLabel14.setText("Evelin Bolanios");

        txtMostrar.setEditable(false);
        txtMostrar.setFont(new java.awt.Font("BankGothic Lt BT", 1, 12)); // NOI18N
        txtMostrar.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnMostrar.setBackground(new java.awt.Color(204, 204, 204));
        btnMostrar.setFont(new java.awt.Font("BankGothic Lt BT", 1, 14)); // NOI18N
        btnMostrar.setText("Inorder");
        btnMostrar.setEnabled(false);
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        txtMostrar1.setEditable(false);
        txtMostrar1.setFont(new java.awt.Font("BankGothic Lt BT", 1, 12)); // NOI18N
        txtMostrar1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnMostrar1.setBackground(new java.awt.Color(204, 204, 204));
        btnMostrar1.setFont(new java.awt.Font("BankGothic Lt BT", 1, 14)); // NOI18N
        btnMostrar1.setText("Inorder");
        btnMostrar1.setEnabled(false);
        btnMostrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir))
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel8))))
                    .addComponent(jLabel9)))
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(btnMostrar)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(jLabel1))
                        .addContainerGap(73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMostrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(btnMostrar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMostrar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIngresar)
                            .addComponent(btnSalir))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(85, 85, 85)
                        .addComponent(btnMostrar)
                        .addGap(11, 11, 11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(txtMostrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        btnIngresar.setEnabled(false);
        try {
            String f = "";
            f = txtNombre.getText(); 
            if (txtNombre.getText().length() > 4) {
                f = txtNombre.getText().substring(0, 5);
            }
            x=0;
            int z = y.ingresar(new Producto("1", txtNombre.getText().toUpperCase(), 1, 1));
            a = z;

            txtNombre.setText("");
            btnMostrar1.setEnabled(true);
            btnMostrar.setEnabled(true);
            String x=y.InordenNR(y.getRaiz());
            if (i == 0) {
                jPanel1.getGraphics().drawRect(z, 1, 40, 14);
                jPanel1.getGraphics().drawString(f.toUpperCase(), z + 1, 12);
                a = z;
                c = jPanel1.getWidth() / 2;
                i = 1;
            } else {
                if (y.getVerificador() == 1) {
                    b = y.getalto();
                    jPanel1.getGraphics().drawLine(a - 20, b - 26, a + 20, b);
                    jPanel1.getGraphics().drawString(f.toUpperCase(), a + 1, b + 12);
                    jPanel1.getGraphics().drawRect(a, b, 40, 14);
                } else {
                    if (y.getVerificador() == 2) {
                        d = y.getalto();
                        jPanel1.getGraphics().drawLine(a + 60, d - 26, a + 20, d);
                        jPanel1.getGraphics().drawString(f.toUpperCase(), a + 1, d + 12);
                        jPanel1.getGraphics().drawRect(a, d, 40, 14);
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "EERRROR de datos");
            txtNombre.setText("");
            System.exit(1);
        }

    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(1);

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        btnMostrar.setEnabled(false);
        txtMostrar.setText(y.InordenNR(y.getRaiz()));

}//GEN-LAST:event_btnMostrarActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        btnIngresar.setEnabled(true);

    }//GEN-LAST:event_txtNombreKeyPressed

    private void btnMostrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrar1ActionPerformed
        if (x < y.tamanio()) {
            txtMostrar1.setText(y.dt(x));
            //jPanel1.getGraphics().drawOval(y.posX(x)-20, y.posy(x)+20, 10, 10);
            jPanel1.getGraphics().fillOval(y.posX(x)-10, y.posy(x)+10, 10, 10);
            System.out.println(""+y.posX(x));
            System.out.println(""+y.posy(x));
            x = x + 1;
             
        } else {
            btnMostrar1.setEnabled(false);
        }

    }//GEN-LAST:event_btnMostrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnMostrar1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtMostrar;
    private javax.swing.JTextField txtMostrar1;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
